<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>127c6067-8f0e-4af6-ab6f-1aeb94c3d8b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-products</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search-products']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c07b7345-0426-44c2-80f9-4c16d656e139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26dacef6-84e4-409d-b6ab-cdf6be9c37e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-products</value>
      <webElementGuid>6be42f25-26c3-4e96-95f4-a13afdbb6eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-search</value>
      <webElementGuid>8c34560f-9fae-42a7-a6df-f255cb7fa032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Search
</value>
      <webElementGuid>311f71d6-6a57-47b2-97b2-fe3884eeb9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-products&quot;)</value>
      <webElementGuid>1a416e29-a4b6-45d6-a5f8-c54569b82a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='search-products']</value>
      <webElementGuid>adf408e1-1b27-4b10-90eb-bdbae28af0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/following::button[1]</value>
      <webElementGuid>9b0ce4bf-ea66-4838-8d6d-0f9e57ff3b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go directly to product SKU'])[1]/following::button[2]</value>
      <webElementGuid>214e8f6b-86a5-40a7-982b-71a19bb2c92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='products'])[1]/preceding::button[1]</value>
      <webElementGuid>7389a35a-0226-428b-aa8c-7193545ec6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>1e56886d-44dd-4a13-8df3-96c73e802f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'search-products' and (text() = '

Search
' or . = '

Search
')]</value>
      <webElementGuid>b6107e7c-c1fa-4107-9f5e-53e8b1f342f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
